tobook:
    resource: "@TobookBundle/Resources/config/routing.yml"
    prefix:   /s

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

users:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

wcs_sms:
    resource: "@WCSSMSBundle/Resources/config/routing.yml"
    prefix:   /

wcs_rating:
    resource: "@WCSRatingBundle/Resources/config/routing.yml"
    prefix:   /

wcs_property:
    resource: "@WCSPropertyBundle/Resources/config/routing.yml"
    prefix:   /

wcs_content:
    resource: "@WCSContentBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"